pipeline {
  agent {
    docker {
      image 'revanth1209/revanth-maven-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/manika-Revanth/jenkins-cicd-pipeline.git'
      }
    }
    stage('Build and Test') {
      steps {
        script {
         // Ensure we're in the correct directory where pom.xml is located
          dir('/var/lib/jenkins/workspace/demo/spring-boot-demo') {
           sh 'mvn clean package'
          }
        } 
      }
    }
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://10.0.2.15:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
    }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "revanth1209/ultimate-cicd:${BUILD_NUMBER}"
      }
      steps {
        script {
            sh 'docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-revanth") {
                dockerImage.push()
            }
        }
      }
    }
    stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "Jenkins-maven-cicd-pipeline"
            GIT_USER_NAME = "manika-Revanth"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                sh '''
                    git config user.email "manikarevanth@gmail.com"
                    git config user.name "manika revanth"
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" jenkins-maven-cicd-pipeline/spring-boot-app-manifests/deployment.yml
                    git add jenkins-maven-cicd-pipeline/spring-boot-app-manifests/deployment.yml
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
            }
        }
    }
  }
}
